DROP DATABASE IF EXISTS AIR;
CREATE DATABASE AIR;
USE AIR;

DROP TABLE IF EXISTS DOMESTIK;
DROP TABLE IF EXISTS INDUSTRI;
DROP TABLE IF EXISTS IRIGASI;
DROP TABLE IF EXISTS AIR_TANAH;
DROP TABLE IF EXISTS DANAU;
DROP TABLE IF EXISTS SUNGAI;
DROP TABLE IF EXISTS PB_AKSI;
DROP TABLE IF EXISTS PENCEGAHAN_BENCANA;
DROP TABLE IF EXISTS BENCANA;
DROP TABLE IF EXISTS INFRASTRUKTUR;
DROP TABLE IF EXISTS PERIZINAN;
DROP TABLE IF EXISTS MONITORING;
DROP TABLE IF EXISTS PENGGUNAAN_AIR;
DROP TABLE IF EXISTS SUMBER_AIR;
DROP TABLE IF EXISTS LEMBAGA_PENGELOLA;
DROP TABLE IF EXISTS WILAYAH;

CREATE TABLE WILAYAH (
    Id_Wilayah VARCHAR (255) PRIMARY KEY,
    Nama_Wilayah VARCHAR(255) NOT NULL
);

CREATE TABLE LEMBAGA_PENGELOLA (
    Id_LP VARCHAR (255) PRIMARY KEY,
    Nama_LP VARCHAR(255) NOT NULL,
    Jalan VARCHAR(255),
    Kota VARCHAR(255)
);

CREATE TABLE SUMBER_AIR (
    Id_SA VARCHAR (255) PRIMARY KEY,
    Nama_SA VARCHAR(255) NOT NULL,
    Lokasi_SA VARCHAR(255),
    Jenis_SA VARCHAR(255),
    Id_Wilayah VARCHAR (255),
    Id_LP VARCHAR (255),
    FOREIGN KEY (Id_Wilayah) REFERENCES WILAYAH(Id_Wilayah),
    FOREIGN KEY (Id_LP) REFERENCES LEMBAGA_PENGELOLA(Id_LP)
);

CREATE TABLE PENGGUNAAN_AIR (
    Id_PA VARCHAR (255) PRIMARY KEY,
    Nama_PA VARCHAR(255) NOT NULL,
    Jenis_PA VARCHAR(255),
    Volume INT,
    Id_SA VARCHAR (255),
    FOREIGN KEY (Id_SA) REFERENCES SUMBER_AIR(Id_SA)
);

CREATE TABLE MONITORING (
    Id_Monitoring VARCHAR (255) PRIMARY KEY,
    Tanggal DATE,
    Parameter VARCHAR(255),
    Id_Hasil VARCHAR (255),
    Nilai DECIMAL (10,2),
    Id_SA VARCHAR (255),
    FOREIGN KEY (Id_SA) REFERENCES SUMBER_AIR(Id_SA)
);

CREATE TABLE PERIZINAN (
    Id_Perizinan VARCHAR (255) PRIMARY KEY,
    Status_Perizinan VARCHAR(255),
    Tgl_Mulai DATE,
    Tgl_Selesai DATE,
    Tipe_Perizinan VARCHAR(255),
    Id_LP VARCHAR (255),
    FOREIGN KEY (Id_LP) REFERENCES LEMBAGA_PENGELOLA(Id_LP)
);

CREATE TABLE INFRASTRUKTUR (
    Id_IA VARCHAR (255) PRIMARY KEY,
    Kondisi_IA VARCHAR(255),
    Jenis_IA VARCHAR(255),
    Kapasitas_IA DECIMAL(10, 2),
    Id_LP VARCHAR (255),
    FOREIGN KEY (Id_LP) REFERENCES LEMBAGA_PENGELOLA(Id_LP)
);

CREATE TABLE BENCANA (
    Id_Bencana VARCHAR (255) PRIMARY KEY,
    Volume_Bencana INT,
    Thn_Bencana INT,
    Tipe_Bencana VARCHAR(255),
    Id_SA VARCHAR (255),
    FOREIGN KEY (Id_SA) REFERENCES SUMBER_AIR(Id_SA)
);

CREATE TABLE PENCEGAHAN_BENCANA (
    Id_PB VARCHAR (255) PRIMARY KEY,
    PenanggungJawab VARCHAR(255),
    Status_PB VARCHAR(255),
    Id_Bencana VARCHAR (255),
    FOREIGN KEY (Id_Bencana) REFERENCES BENCANA(Id_Bencana)
);

CREATE TABLE PB_AKSI (
    Id_PB VARCHAR (255),
    Aksi VARCHAR(255),
    PRIMARY KEY (Id_PB, Aksi),
    FOREIGN KEY (Id_PB) REFERENCES PENCEGAHAN_BENCANA(Id_PB)
);

CREATE TABLE DANAU (
    Id_SA VARCHAR (255) PRIMARY KEY,
    LuasDanau DECIMAL(10, 2),
    FOREIGN KEY (Id_SA) REFERENCES SUMBER_AIR(Id_SA)
);

CREATE TABLE AIR_TANAH (
    Id_SA VARCHAR (255) PRIMARY KEY,
    Kedalaman DECIMAL(10, 2),
    FOREIGN KEY (Id_SA) REFERENCES SUMBER_AIR(Id_SA)
);

CREATE TABLE SUNGAI (
    Id_SA VARCHAR (255) PRIMARY KEY,
    Panjang DECIMAL(10, 2),
    FOREIGN KEY (Id_SA) REFERENCES SUMBER_AIR(Id_SA)
);

CREATE TABLE IRIGASI (
    Id_PA VARCHAR (255) PRIMARY KEY,
    LuasLahan DECIMAL(10, 2),
    FOREIGN KEY (Id_PA) REFERENCES PENGGUNAAN_AIR(Id_PA)
);

CREATE TABLE DOMESTIK (
    Id_PA VARCHAR (255) PRIMARY KEY,
    JumlahPengguna INT,
    FOREIGN KEY (Id_PA) REFERENCES PENGGUNAAN_AIR(Id_PA)
);

CREATE TABLE INDUSTRI (
    Id_PA VARCHAR (255) PRIMARY KEY,
    Instansi VARCHAR(255),
    FOREIGN KEY (Id_PA) REFERENCES PENGGUNAAN_AIR(Id_PA)
);
